### PR TITLE
Honor schema name at time of migration

### PR DESCRIPTION
**Pull request by shehabghazy**
we need to migrate automatisch in a specific schema so this is a small modification allowing it to honor schema name at time of migration, so if there is a database already exists and we need to migrate automatisch's tables on it separately in a specific schema it will be easy

### CODE REVIEW

**Comment by farukaydin** [comment]
Hey @shehabghazy, to understand the use case better, is there any specific reason not to use public schema but another one?

**Comment by shehabghazy** [comment]
Hey @farukaydin , we have our own database which has multiple schemas and has already some tables in schema public, we need to migrate automatisch on the same db but it will cause a conflict in table names in schema public and also it will be some kind of disorganization.
so it is better to migrate it on a seperated schema, what I have done is just if there is DATABASE_SCHEMA in env variables the migration will consider it, if not it will work nomrally with public scheam

**Comment by farukaydin** [comment]
@shehabghazy, could you allow me to push new commits into your PR to have some changes on top of yours? You can check [here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests) to learn how to do it in case you're not familiar with.

**Comment by shehabghazy** [comment]
@farukaydin done .. I have allowed edits from maintainers

**Comment by farukaydin** [comment]
@shehabghazy thanks, I have applied my changes, basically it's the same but the only difference is using `POSTGRES_SCHEMA` env variable instead of `DATABASE_SCHEMA`. 

Thanks again for your contribution.

**Comment by shehabghazy** [comment]
@farukaydin you are welcome, it is my pleasure to add a contribution in a perfect tool like automatisch .. keep going

**Pull request merged**
