### PR TITLE
feat: add postgres integration

### PR DESCRIPTION
**Pull request by shehabghazy**
Here is an integration with postgreSQL db with 4 actions:
- Execute any SQL normal queries
- Insert
- Update
- Delete
Also it is available to add any run-time configuration parameter  to SET before executing the actions

The linked issue : https://github.com/automatisch/automatisch/issues/923

### CODE REVIEW

**Review by barinali — CHANGES_REQUESTED** [review]
Thanks for your contribution, @shehabghazy! I'm submitting some remarks in advance while reviewing the remaining part of the pull request.

**Comment by barinali** [comment]
@shehabghazy, I've rebased the branch against the `main` branch as it was outdated. We follow the conventional commit messages in the Automatisch code repository. So, I'd appreciate it if you could rephrase your commit message to something like `feat(postgresql): add auth and primitive actions`.

Besides this, there are some places I'd like to test and refactor a bit. Therefore, I'm considering pushing some changes to your branch. As I see you allowed maintainers to edit the pull request, I presume it's fine by you. Otherwise, let me know.

**Comment by barinali** [comment]
Hey @shehabghazy, I have pushed some commits over your contribution. Introducing interactive where clauses along with some rewording and refactoring. I've done some testing which seems fine so far. However, I have not tried all the where clause operators. I'll take another look at this pull request tomorrow. Until then, do you think you could give it a try and let me know if you notice anything off?

**Comment by shehabghazy** [comment]
hey @barinali hope you have got well, 
I apreciate your effort to enhance Automatisch, I have looked at your commits and the parts that you have applied some refactoring on, and it is very good to enhance it like this.. of cource I will inform you if I faced any problema while testing

**Review by farukaydin — APPROVED** [review]

**Review by barinali — APPROVED** [review]

**Pull request merged**
