### PR TITLE
Fix issue #1933

### PR DESCRIPTION
**Pull request by jmas**
Problem with rendering in DynamicField component with long variables #1933

This fix makes DynamicField look in next way:

Знімок екрана 2024-06-13 о 03 31 43

### CODE REVIEW

**Review by kattoczko — CHANGES_REQUESTED** [review]
From what I've tested the code changes don't fix the issue.

**Comment by barinali** [comment]
> [CLA assistant check](https://cla-assistant.io/automatisch/automatisch?pullRequest=1934) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/automatisch/automatisch?pullRequest=1934) before we can accept your contribution.You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/automatisch/automatisch?pullRequest=1934) it.

Hey @jmas, I appreciate it. Thank you for your contribution to Automatisch! May I ask if you can proceed with the CLAassistant?

I quoted the reference bot-message from the CLAassistant above.

**Comment by jmas** [comment]
@barinali Thank you for point me on it. I signed it! Check: https://github.com/automatisch/automatisch/pull/1934#issuecomment-2164137434

**Review by kattoczko — APPROVED** [review]
Looks good to me now, thank you for the fix!

**Pull request merged**
